Fix Spree::Entities load
Before this commit the task

`bundle exec rake solidus_avatax_certified:load_seeds`

failed with:

```
rake aborted!
NameError: uninitialized constant SolidusAvataxCertified::Spree::AvalaraEntityUseCode
./bin/bundle:3:in `load'
./bin/bundle:3:in `<main>'

Caused by:
NameError: uninitialized constant SolidusAvataxCertified::Spree::AvalaraEntityUseCode
./bin/bundle:3:in `load'
./bin/bundle:3:in `<main>'
Tasks: TOP => solidus_avatax_certified:load_seeds
(See full trace by running task with --trace)
```

This commit fixes it.